/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package projetjava;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;

/**
 *
 * @author Mokh
 */
public class promo extends javax.swing.JFrame {

    /**
     * Creates new form promo
     */
    public String prixactuel(String ch)
    {
    {
        
String url = "jdbc:mysql://localhost:3306/projet";
String login="root";
String password="";

try {
   Class.forName("com.mysql.jdbc.Driver");

Connection con = DriverManager.getConnection(url, login, password);
System.out.println("connection validé au DESTINATION");
Statement stmt2 = con.createStatement();

PreparedStatement stmt= con.prepareStatement("SELECT PRIX from destinations where destinations.NOM='"+ch+"'");

ResultSet rs=stmt.executeQuery();
if(rs.next()){
return(rs.getString("PRIX"));
}
con.close();
stmt.close();
stmt.close();
stmt2.close();

} // terminer le try
catch (Exception e) {
System.out.println(" Attention l'exception : " + e + "est arrivée");
} // fin de la capture de l'exception
return null;
}
    }
    public void AjouterBase(String dest,String NPrix)
{
    {
        
String url = "jdbc:mysql://localhost:3306/projet";
String login="root";
String password="";

try {
   Class.forName("com.mysql.jdbc.Driver");

Connection con = DriverManager.getConnection(url, login, password);
System.out.println("connection validé au DESTINATION");
Statement stmt2 = con.createStatement();

PreparedStatement stmt= con.prepareStatement("UPDATE projet.destinations SET `PRIX` ="+NPrix+
        " WHERE destinations.NOM ='"+dest+"'");

stmt.execute();
//ResultSet rs=stmt.executeQuery();
//if(rs.next()){
//return(rs.getString("PRIX"));
//}
con.close();
stmt.close();
stmt.close();
stmt2.close();

} // terminer le try
catch (Exception e) {
System.out.println(" Attention l'exception : " + e + "est arrivée");
} // fin de la capture de l'exception
}    
    
    }

    public promo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        choice1 = new java.awt.Choice();
        textField1 = new java.awt.TextField();
        textField2 = new java.awt.TextField();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        Valider = new java.awt.Button();
        label3 = new java.awt.Label();
        Valider1 = new java.awt.Button();

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        choice1.add("Turquie");
        choice1.add("Singapour");
        choice1.add("Egypte");
        choice1.add("Grece");
        choice1.add("Italie");
        choice1.setBackground(new java.awt.Color(255, 255, 204));
        choice1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                choice1MouseClicked(evt);
            }
        });
        choice1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                choice1ItemStateChanged(evt);
            }
        });

        textField1.setText("");
        textField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField1ActionPerformed(evt);
            }
        });

        label1.setBackground(new java.awt.Color(255, 255, 204));
        label1.setText("Prix Actuelle");

        label2.setBackground(new java.awt.Color(255, 255, 204));
        label2.setForeground(new java.awt.Color(255, 0, 0));
        label2.setText("NouveauPrix");

        Valider.setBackground(new java.awt.Color(255, 255, 153));
        Valider.setLabel("Valider");
        Valider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ValiderActionPerformed(evt);
            }
        });

        label3.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        label3.setForeground(new java.awt.Color(0, 0, 255));
        label3.setPreferredSize(new java.awt.Dimension(38, 50));
        label3.setText("Nos Destinations");

        Valider1.setBackground(new java.awt.Color(255, 255, 153));
        Valider1.setLabel("Previous");
        Valider1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Valider1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(choice1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(label2, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                    .addComponent(label1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textField2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textField1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Valider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(81, 81, 81)
                        .addComponent(Valider, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(textField1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(choice1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textField2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Valider, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(Valider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void choice1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_choice1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_choice1MouseClicked

    private void choice1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_choice1ItemStateChanged
        // TODO add your handling code here:
        //textField1 = new java.awt.TextField();
if(this.choice1.getSelectedItem()=="Tunisie"){
String msg=prixactuel("Tunisie");
textField1.setText(msg);
}
else if(this.choice1.getSelectedItem()=="Turquie"){
String msg=prixactuel("Turquie");
textField1.setText(msg);
}
else if(this.choice1.getSelectedItem()=="Bongkok"){
String msg=prixactuel("Bongkok");
textField1.setText(msg);
}
else if(this.choice1.getSelectedItem()=="Italie"){
String msg=prixactuel("Italie");
textField1.setText(msg);
}
else if(this.choice1.getSelectedItem()=="Egypte"){
String msg=prixactuel("Egypte");
textField1.setText(msg);
}
else if(this.choice1.getSelectedItem()=="Casablanca"){
String msg=prixactuel("Casablanca");
textField1.setText(msg);
}
else if(this.choice1.getSelectedItem()=="Grece"){
String msg=prixactuel("Grece");
textField1.setText(msg);
}
else if(this.choice1.getSelectedItem()=="Singapour"){
String msg=prixactuel("Singapour");
textField1.setText(msg);
}

    }//GEN-LAST:event_choice1ItemStateChanged

    private void ValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ValiderActionPerformed
        // TODO add your handling code here:
         String NPrix=this.textField2.getText();
       if(NPrix!=""){
           if(this.choice1.getSelectedItem()=="Tunisie"){
                AjouterBase("Tunisie", NPrix);}
           else if(this.choice1.getSelectedItem()=="Turquie")
           {   AjouterBase("Turquie", NPrix);}
           else if(this.choice1.getSelectedItem()=="Singapour")
           {   AjouterBase("Singapour", NPrix);}
           else if(this.choice1.getSelectedItem()=="Egypte")
           {AjouterBase("Egypte", NPrix);}
           else if(this.choice1.getSelectedItem()=="Grece")
           {   AjouterBase("Grece", NPrix);}
           else if(this.choice1.getSelectedItem()=="Italie")
           {   AjouterBase("Italie", NPrix);}
           else if(this.choice1.getSelectedItem()=="Casablanca")
           {   AjouterBase("Casablanca", NPrix);}


               }
       


    }//GEN-LAST:event_ValiderActionPerformed

    private void textField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField1ActionPerformed

    private void Valider1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Valider1ActionPerformed
        // TODO add your handling code here:
    this.setVisible(false);
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExecutableRequetes().setVisible(true);
            }
        });
    
    }//GEN-LAST:event_Valider1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(promo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(promo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(promo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(promo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new promo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button Valider;
    private java.awt.Button Valider1;
    private java.awt.Choice choice1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.TextField textField1;
    private java.awt.TextField textField2;
    // End of variables declaration//GEN-END:variables
}
